config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :chatgpt do
    collection do
      get :choose
      get :begin
    end
  end

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatgpt/index.html.erb
<h1>Playing with Chat GPT</h1>

<div style="width: 400px">
  <div class="row">
    <div class="col-md-4">
      <div class="card shadow mb-4">
        <div class="card-body">
          <div class="tictactoe_btn" id="1" style="width: 70px; height: 30px; border: 1px solid;cursor: pointer;display: flex;justify-content: center;"></div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card shadow mb-4">
        <div class="card-body">
          <div class="tictactoe_btn" id="2" style="width: 70px; height: 30px; border: 1px solid;cursor: pointer;display: flex;justify-content: center;"></div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card shadow mb-4">
        <div class="card-body">
          <div class="tictactoe_btn" id="3" style="width: 70px; height: 30px; border: 1px solid;cursor: pointer;display: flex;justify-content: center;"></div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="card shadow mb-4">
        <div class="card-body">
          <div class="tictactoe_btn" id="4" style="width: 70px; height: 30px; border: 1px solid;cursor: pointer;display: flex;justify-content: center;"></div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card shadow mb-4">
        <div class="card-body">
          <div class="tictactoe_btn" id="5" style="width: 70px; height: 30px; border: 1px solid;cursor: pointer;display: flex;justify-content: center;"></div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card shadow mb-4">
        <div class="card-body">
          <div class="tictactoe_btn" id="6" style="width: 70px; height: 30px; border: 1px solid;cursor: pointer;display: flex;justify-content: center;"></div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="card shadow mb-4">
        <div class="card-body">
          <div class="tictactoe_btn" id="7" style="width: 70px; height: 30px; border: 1px solid;cursor: pointer;display: flex;justify-content: center;"></div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card shadow mb-4">
        <div class="card-body">
          <div class="tictactoe_btn" id="8" style="width: 70px; height: 30px; border: 1px solid;cursor: pointer;display: flex;justify-content: center;"></div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card shadow mb-4">
        <div class="card-body">
          <div class="tictactoe_btn" id="9" style="width: 70px; height: 30px; border: 1px solid;cursor: pointer;display: flex;justify-content: center;"></div>
        </div>
      </div>
    </div>
  </div>
</div>

<h1>ChatGpt responses</h1>
<div id="responses">

</div>

<% content_for :javascript do %>
  <script type="application/javascript">
      // $(document).ready(function() {
      //     $.ajax({
      //         url: "/chatgpt/begin",
      //         type: "GET",
      //         data: {  },
      //         success: function(data) {
      //             console.log(data.response);
      //             $("#responses").append("<p>" + data.response + "</p>");
      //             var choice = data.response.match(/\d+/g);
      //             $("#" + choice).html("O");
      //             $("#" + choice).prop("disabled", true);
      //         }
      //     });
      // });

      $(".tictactoe_btn").click(function() {
          var id = $(this).attr("id");
          $(this).html("X");
          $(this).prop("disabled", true);
          $.ajax({
              url: "/chatgpt/choose?choice=" + id,
              type: "GET",
              data: {  },
              success: function(data) {
                  console.log(data.choice);
                  $("#responses").append("<p>" + data.choice + "</p>");
                  var choice = data.choice.match(/\d+/g);
                  $("#" + choice).html("O");
                  $("#" + choice).prop("disabled", true);
              }
          });
      });
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails7hotwire</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link href="/theme/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="/theme/css/sb-admin-2.min.css" rel="stylesheet">
  <link href="/css/tags.css" rel="stylesheet">
</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

  <!-- Sidebar -->
  <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
      <div class="sidebar-brand-icon rotate-n-15">
        <i class="fas fa-laugh-wink"></i>
      </div>
      <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
      <a class="nav-link" href="index.html">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
      Menu
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseOne"
         aria-expanded="true" aria-controls="collapseOne">
        <i class="fas fa-fw fa-cog"></i>
        <span>Tic-Tac-Toe</span>
      </a>
      <div id="collapseOne" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
          <h6 class="collapse-header">Play with</h6>
          <%= link_to "Chat GPT", chatgpt_index_path, class: 'collapse-item' %>
        </div>
      </div>
    </li>

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
      <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

    <!-- Sidebar Message -->

  </ul>
  <!-- End of Sidebar -->

  <!-- Content Wrapper -->
  <div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">

      <!-- Topbar -->
      <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
          <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">

          <!-- Nav Item - Search Dropdown (Visible Only XS) -->
          <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                 aria-labelledby="searchDropdown">
              <form class="form-inline mr-auto w-100 navbar-search">
                <div class="input-group">
                  <input type="text" class="form-control bg-light border-0 small"
                         placeholder="Search for..." aria-label="Search"
                         aria-describedby="basic-addon2">
                  <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                      <i class="fas fa-search fa-sm"></i>
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </li>

          <div class="topbar-divider d-none d-sm-block"></div>

          <!-- Nav Item - User Information -->
          <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="mr-2 d-none d-lg-inline text-gray-600 small"></span>
              <img class="img-profile rounded-circle"
                   src="/theme/img/undraw_profile.svg">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                 aria-labelledby="userDropdown">
              <%#= button_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>

        </ul>

      </nav>
      <!-- End of Topbar -->

      <!-- Begin Page Content -->
      <div class="container-fluid">
        <%= yield %>
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- End of Main Content -->

    <!-- Footer -->
    <footer class="sticky-footer bg-white">
      <div class="container my-auto">
        <div class="copyright text-center my-auto">
          <span>Copyright &copy; Your Website 2021</span>
        </div>
      </div>
    </footer>
    <!-- End of Footer -->

  </div>
  <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
        <a class="btn btn-primary" href="login.html">Logout</a>
      </div>
    </div>
  </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="/theme/vendor/jquery/jquery.min.js"></script>
<script src="/theme/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="/theme/vendor/jquery-easing/jquery.easing.min.js"></script>
<!-- Custom scripts for all pages-->
<script src="/theme/js/sb-admin-2.min.js"></script>
<script src="/js/tags.js"></script>
<%= yield :javascript %>

</body>
</html>